### ISSUE TITLE
Implement all play descriptions

### ISSUE THREAD

**Issue by eugene-bulkin** [eugene-bulkin/retrosheet-rs#2]
There are currently play descriptions missing:

- [x] Catcher interference (see #8)
- [x] Intentional walk (see #8)
- [x] Ground rule double (see #8)
- [x] Defensive indifference (see #9)
- [x] Other advance (the `OA` code, which is just some other thing happening) (see #9)
- [x] Runner picked off (see #9)
- [x] Lined into double/triple plays (see #10)
- [x] Triple plays (see #11)
